- build.gradle
- src/main/java/com/code_inspector/plugins/intellij/annotators/CodeInspectionAnnotation.java
- src/main/java/com/code_inspector/plugins/intellij/annotators/CodeInspectorExternalAnnotator.java
- src/main/java/com/code_inspector/plugins/intellij/graphql/CodeInspectorApiUtils.java
- src/test/java/com/code_inspector/plugins/intellij/graphql/CodeInspectorApiUtilsTest.java
Add mockito as a dependency in order to mock objects for testing purposes
- Add functions to map ComplexFunction and LongFunction objects into `CodeInspectionAnnotation`
- Add tests for mapping functions - `mapLongFunction` and `mapComplexFunction`
- Surface complex and long function annotations in IntelliJ
> Map complex and long functions

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/main/graphql/com/code_inspector/api/CreateFileAnalysis.graphql
- src/main/java/com/code_inspector/plugins/intellij/annotators/CodeInspectorExternalAnnotator.java
- src/main/java/com/code_inspector/plugins/intellij/graphql/CodeInspectorApiImpl.java
- src/main/java/com/code_inspector/plugins/intellij/ui/NotificationUtils.java
- No longer use a project to detect if notification was already sent (Closes: Investigate crash from client #31)
- Use real-time feedback pipeline and correctly passes project as argument (Closes: Passing project for real-time feedback #32)
> Fix crash, use real-time feedback and bump dependencies

- CHANGELOG.md
- src/main/java/com/code_inspector/plugins/intellij/annotators/CodeInspectionAnnotation.java
- src/main/java/com/code_inspector/plugins/intellij/annotators/CodeInspectorExternalAnnotator.java
- src/main/java/com/code_inspector/plugins/intellij/graphql/CodeInspectorApiUtils.java
- src/test/java/com/code_inspector/plugins/intellij/annotators/CodeInspectionAnnotationTest.java
Sometimes, we have two rules producing the same text. We want to remove that in order to make sure the user experience is better with only one warning with the same message.
In this change, we make sure we have only one report for the same message.
Adding test to check we are correctly doing the filtering.
> Remove annotation with the same text

- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/SnippetToolWindowFactory.java
- src/main/java/io/codiga/plugins/jetbrains/cache/CacheRefreshEditorListener.java
- src/main/java/io/codiga/plugins/jetbrains/cache/ShortcutCache.java
- src/main/java/io/codiga/plugins/jetbrains/cache/TypedKeyHandler.java
- src/main/resources/META-INF/plugin.xml
✅ register user activity when the user changes a window or type a character
✅ do not check the cache if there is no user activity after 10 minutes
> do not refresh the shortcut cache if there is no user activity

- gradle.properties
- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/SnippetPanel.java
- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/SnippetToolWindow.java
- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/SnippetToolWindowFactory.java
- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/SnippetToolWindowFileEditorManagerListener.java
- src/main/java/io/codiga/plugins/jetbrains/actions/use_recipe/UseRecipeSearchModel.java
- src/main/java/io/codiga/plugins/jetbrains/starter/AppStarter.java
- src/main/java/io/codiga/plugins/jetbrains/topics/SnippetToolWindowFileChangeNotifier.java
- src/main/java/io/codiga/plugins/jetbrains/utils/RecipeUtils.java
**Problem**
The snippet search is sometimes picking up/editing files that are not in the current window.
**Solution**
When preview or insert a snippet, always take the current window.
> fix: snippet search window

- src/test/java/io/codiga/plugins/jetbrains/assistant/transformers/VariableIndentationTest.java
- src/test/java/io/codiga/plugins/jetbrains/completion/CodigaCompletionProviderTest.java
- src/test/java/io/codiga/plugins/jetbrains/completion/inline/InlineCompletionTest.java
- src/test/java/io/codiga/plugins/jetbrains/testutils/TestBase.java
- src/test/java/io/codiga/plugins/jetbrains/testutils/TestVariableMacroGeneric.java
- src/test/java/io/codiga/plugins/jetbrains/testutils/TestVariableTransformerGeneric.java
- Update test data path retrieval logic in `TestBase`.
- Remove `@Ignore` annotation, constructor and `setUp()` from ignored test classes, and make them abstract instead.
- Make some test classes extend `TestBase` to use the new data path retrieval logic.
> Deduplication and cleanup regarding TestBase

- CHANGELOG.md
- README.md
- build.gradle.kts
- gradle.properties
- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/SnippetPanel.form
- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/SnippetPanel.java
- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/SnippetToolWindow.java
- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/service/DefaultFileTypeService.java
- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/service/JavaFileTypeService.java
- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/service/PythonFileTypeService.java
- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/service/SyntaxHighlightFileTypeService.java
- src/main/java/io/codiga/plugins/jetbrains/utils/LanguageUtils.java
- src/main/resources/META-INF/java-features.xml
- src/main/resources/META-INF/plugin.xml
- src/main/resources/META-INF/python-features.xml
- Lowered the gradle-intellij-plugin version to 1.6.0 so that the tool window works without encountering the `$$$getFont$$$` issue.
- Lowered the platform version to 2021.3, so that
- it matches the `sinceBuild` version,
- the Python dependency version can be specified properly. It is unclear if the Codiga plugin would run into any errors if the Python plugin version is compatible only with later versions e.g. 2022.2, but the IDE it works in is an earlier one e.g. 2021.3. So this should keep us on the safe side.
- Removed 2021.2 from the plugin verifier versions, since the Codiga plugin is compatible from 2021.3.
- Added Java and Python as optional dependencies in `build.gradle.kts` and `plugin.xml`, due to the variety of IDEs the Codiga plugin supports.
- Replaced the code snippet field …
> Snippet search syntax highlighting

- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotationFix.java
- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotator.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieAnnotation.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieAnnotationJetBrains.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieConstants.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosiePosition.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieRequest.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieResponse.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieViolation.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieViolationFix.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieViolationFixEdit.java
- src/main/java/io/codiga/plugins/jetbrains/services/Rosie.java
- src/main/java/io/codiga/plugins/jetbrains/services/RosieImpl.java
- src/main/java/io/codiga/plugins/jetbrains/utils/RosieUtils.java
- src/test/java/io/codiga/plugins/jetbrains/services/RosieTest.java
- Added javadocs to a handful of Rosie related classes and fields.
- Simplified the constructors of `RosieAnnotation` and `RosieAnnotationJetBrains`, so that less parameters must be passed in.
- Marked the `Rosie#getAnnotations()` method as returning `@NotNull`, as per current implementation details.
- Marked constants in `RosieConstants` final.
- `RosieImpl`
- Gson is now a static final field.
- A few other minor adjustments.
> Rosie documentation and code refinement

- src/main/java/io/codiga/plugins/jetbrains/annotators/AnnotationFixOpenBrowser.java
- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotator.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieAnnotation.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieAnnotationJetBrains.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosiePosition.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieViolation.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieViolationFixEdit.java
- src/test/data/rosieannotator/highlight_for_multiple_violations.py
- src/test/data/rosieannotator/highlight_for_single_violation.py
- src/test/data/rosieannotator/no_highlight_for_end_offset_outside.py
- src/test/data/rosieannotator/no_highlight_for_no_violation.py
- src/test/data/rosieannotator/no_highlight_for_start_offset_outside.py
- src/test/data/rosieannotator/text_insertion_fix.py
- src/test/data/rosieannotator/text_removal_fix_ranges_matching.py
- src/test/data/rosieannotator/text_removal_fix_ranges_not_matching.py
- src/test/data/rosieannotator/text_replacement_fix_ranges_matching.py
- src/test/data/rosieannotator/text_replacement_fix_ranges_not_matching.py
- src/test/java/io/codiga/plugins/jetbrains/annotators/AnnotationFixOpenBrowserTest.java
- src/test/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotatorTest.java
- src/test/java/io/codiga/plugins/jetbrains/services/RosieTest.java
- Simplified a few classes using Lombok.
- `RosieAnnotator`
- Added integration tests.
- Filtered out annotations in which the line start offset in the editor can't be calculated due to out-of-range, start or end line offset received from the server.
- Added integration tests for `AnnotationFixOpenBrowser`.
- Simplfied the constructor of `RosieAnnotationJetBrains`.
> Rosie integration tests

- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieRulesCache.java
- src/main/java/io/codiga/plugins/jetbrains/starter/RosieRulesCacheUpdateHandler.java
- src/main/java/io/codiga/plugins/jetbrains/starter/RosieRulesCacheUpdater.java
- src/test/data/rosiecacheupdater/codiga.yml
- src/test/data/rosiecacheupdater/noruleset/codiga.yml
- src/test/java/io/codiga/plugins/jetbrains/graphql/CodigaApiTest.java
- src/test/java/io/codiga/plugins/jetbrains/graphql/RulesetsForClientTestSupport.java
- src/test/java/io/codiga/plugins/jetbrains/starter/RosieRulesCacheUpdateHandlerNoRulesetTest.java
- src/test/java/io/codiga/plugins/jetbrains/starter/RosieRulesCacheUpdateHandlerTest.java
- Added integration tests for the cache updater, for both flows:
- `codiga.yml` is modified
- rules changed on the server
- `RosieRulesCache`
- Adjusted the stamp default values.
- Resetting the `lastUpdatedTimeStamp` during cache clear, regardless the cache was clear or not.
- `RosieRulesCacheUpdater`
- Extracted the cache update logic to a new class called `RosieRulesCacheUpdateHandler`, so that it can be tested separately from the background task.
- The background task is now turned off in case of integration tests, so that it doesn't interfere with test logic.
- `RosieRulesCacheUpdateHandler`
- Added extra validation on `VirtualFile` level, so that if `codiga.yml` does not exist (regardless if the `YAMLFile` instance is still present), the cache gets cleared.
- If there is an empty …
> Rosie rules cache updater tests

- src/main/java/io/codiga/plugins/jetbrains/completion/inline/InlineDocumentListener.java
- src/main/java/io/codiga/plugins/jetbrains/utils/LanguageUtils.java
- src/test/java/io/codiga/plugins/jetbrains/completion/inline/InlineCompletionTest.java
- src/test/java/io/codiga/plugins/jetbrains/utils/LanguageUtilsTest.java
- `LanguageUtils`
- Added the `containsTodoKeyword()` method to check whether a line contains `todo` or `fixme` kwywords.
- Simplified the `numberOfWordsInComment()` method.
- `InlineDocumentListener`
- Snippet preview is no longer triggered when the comment line contains a `todo` or `fixme` keyword.
- Extracted the line retrieval and completion eligibility checking into a separate method.
- Removed a null check, since `Document#getText()`, by its method contract, returns non-null value.
- Added unit and integration tests.
> Don't trigger inline completion for comments containing todo keywords

- src/main/java/io/codiga/plugins/jetbrains/services/RosieImpl.java
- Wrap `PsiFile#getText()` call in `ReadAction` in `RosieImpl` to prevent *Read access is allowed from inside read-action (or EDT) only* errors.
> Wrap PsiFile#getText call in ReadAction

- .run/Run Build Plugin.run.xml
- .run/Run IDE with Plugin.run.xml
- .run/Run Plugin Tests.run.xml
- .run/Run Verifications.run.xml
- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/SnippetToolWindow.java
- src/main/java/io/codiga/plugins/jetbrains/assistant/transformers/VariableTransformerRndNumber.java
- src/main/java/io/codiga/plugins/jetbrains/assistant/transformers/VariableTransformerSecondsUnix.java
- src/main/java/io/codiga/plugins/jetbrains/dependencies/AbstractDependency.java
- src/main/java/io/codiga/plugins/jetbrains/dependencies/DependencyManagement.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieRequest.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieRuleResponse.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieViolationFix.java
- src/main/java/io/codiga/plugins/jetbrains/topics/ApiKeyChangeNotifier.java
- src/main/java/io/codiga/plugins/jetbrains/topics/ChangeNotifier.java
- src/main/java/io/codiga/plugins/jetbrains/topics/CodigaEnabledStatusNotifier.java
- src/main/java/io/codiga/plugins/jetbrains/topics/SnippetToolWindowFileChangeNotifier.java
- src/main/java/io/codiga/plugins/jetbrains/topics/VisibilityKeyChangeNotifier.java
- src/main/java/io/codiga/plugins/jetbrains/ui/StatusBar.java
- src/main/java/io/codiga/plugins/jetbrains/utils/CodeImportUtils.java
- Removed unused imports.
- Simplified a few model classes with Lombok.
- Added IntelliJ Run Configurations specific to plugin development.
- This way they persist in the Run Configuration dropdown.
- Introduced a parent interface, `ChangeNotifier`, for topic listener classes. This way
- the implementation of those classes is simplfied,
- since `beforeAction()` is not called anywhere now, the notifier types can be handled as functional interfaces and lambda expressions at their places of usage.
- `SnippetToolWindow`
- Replaced some null checks with an `Optional` chain.
- Replaced `DocumentListener` with `DocumentAdapter` to have a simpler code there.
> Housekeeping and finetuning

- src/main/java/io/codiga/plugins/jetbrains/actions/snippet_search/SnippetToolWindow.java
- `SnippetToolWindow`
- The `updateUser()` method now removes the `MouseListener` from the logged-in label before adding it. This solves the problem that upon clicking the label, Codiga Hub was opened multiple times at once
> Fix Snippet Search logged in text click

- CHANGELOG.md
- src/main/java/io/codiga/plugins/jetbrains/settings/application/AppSettingsComponent.java
- src/main/java/io/codiga/plugins/jetbrains/settings/application/AppSettingsConfigurable.java
- src/main/java/io/codiga/plugins/jetbrains/ui/StatusBar.java
- src/main/java/io/codiga/plugins/jetbrains/ui/UIConstants.java
- `AppSettingsComponent` and `AppSettingsConfigurable`
- Fixed a few typos.
- Removed an unused logger field.
- Moved the Codiga completion related checkbox components into a `ButtonGroup`. This automatically makes sure that only one of the `RadioButton`s in that group can be selected at a time, instead of having to manually update each button's selected state.
- **Bugfix**: there was an issue that when the settings page was opened with Codiga disabled, the code completion and inline completion checkboxes were still enabled.
- Improved the settings UI.
- Moved the checkbox and radiobutton labels into the constructor's of those components, instead of using a separate `JLabel` for each of them. This made both the UI and the code clearer.
- `StatusBar`
- **Bugfix**: the status bar icon's …
> Settings UI enhancements and status bar bugfix

- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotationFix.java
- src/test/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotationFixTest.java
- src/test/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotatorTest.java
- `RosieAnnotationFix`
- If any offset in any edits of a `RosieViolationFix` is out of the files range and would result in an `IndexOutOfBoundsException`, we should an error hint in the editor, at the place where the quick fix was invoked.
- Moved some tests from `RosieAnnotatorTest` to `RosieAnnotationFixTest`.
Said error hint:
> Display error hint in the editor when a Rosie annotation fix can't be applied

- src/main/java/io/codiga/plugins/jetbrains/annotators/AnnotationFixOpenBrowser.java
- src/main/java/io/codiga/plugins/jetbrains/annotators/DisableRosieAnalysisFix.java
- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotator.java
- src/test/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotatorTest.java
- Updated the titles of `AnnotationfixOpenBrowser` and `DisableRosieAnalysisFix`, including adding the associated rules' names to them.
> Add rule names to the Rosie quick fix titles

- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieRulesCache.java
- src/main/java/io/codiga/plugins/jetbrains/rosie/CodigaConfigFileUtil.java
- src/main/java/io/codiga/plugins/jetbrains/starter/RosieRulesCacheUpdateHandler.java
- src/main/java/io/codiga/plugins/jetbrains/starter/RosieStartupActivity.java
- Removed the `CachedValueProvider` based caching of the ruleset names because I encountered a invalid cached PSI/`YAMLFile` instance related problem, that I had no `CachedValueProvider` based solution for.
- The cache implementation is moved to `RosieRulesCache` from `CodigaConfigFileUtil`.
> Move ruleset name caching implementation from CachedValueProvider

- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieRulesCacheValue.java
- src/main/java/io/codiga/plugins/jetbrains/model/rosie/RosieRule.java
- src/test/java/io/codiga/plugins/jetbrains/annotators/RosieRulesCacheTest.java
- Updated the `RosieRule` id, so that it is sent in the form of ruleset/rulename, e.g. *python-best-practices/some-python-rule*.
> Update Rosie rule name

- CHANGELOG.md
- src/main/java/io/codiga/plugins/jetbrains/reference/CodigaRulesetReferenceContributor.java
- src/main/java/io/codiga/plugins/jetbrains/rosie/CodigaConfigFileUtil.java
- src/main/resources/META-INF/yaml-features.xml
- src/test/java/io/codiga/plugins/jetbrains/reference/CodigaRulesetReferenceContributorTest.java
- Introduced `CodigaRulesetReferenceContributor` that adds a `WebReference` to ruleset names. `WebReference` makes it possible to open a URL in the browser upon clicking on an element.
- Reference is not added to invalid ruleset names.
> Add web references to ruleset names

- src/main/java/io/codiga/plugins/jetbrains/Constants.java
- src/main/java/io/codiga/plugins/jetbrains/settings/application/AppSettingsState.java
- Removed the `PasswordSafe` based solution, and move the api token to `AppSettingsState`.
- Although `PasswordUtil` is deprecated and `PasswordSafe` is recommended to be used instead, I use this util for encoding/decoding, since it is a less common type of chips to lock that door with, than base64.
> Use application settings to store the api token

- src/main/java/io/codiga/plugins/jetbrains/settings/application/AppSettingsState.java
- src/test/java/io/codiga/plugins/jetbrains/assistant/transformers/VariableIndentationTest.java
- src/test/java/io/codiga/plugins/jetbrains/completion/CodigaCompletionProviderTest.java
- src/test/java/io/codiga/plugins/jetbrains/completion/inline/InlineCompletionTest.java
- `AppSettingsState`
- Set the default value of both inline the shortcuts completion to `false`/disabled.
> Disable inline and code completion by default

- src/main/java/io/codiga/plugins/jetbrains/starter/AppStarter.java
- `AppStarter`
- Added `project.isDisposed()` checks both before starting the updater, and for when the updater is already running.
> Check if project is disposed before starting the shortcut cache updater.

- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotationFix.java
- src/test/data/rosieannotator/text_insertion_fix_null_end.py
- src/test/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotationFixTest.java
- src/test/java/io/codiga/plugins/jetbrains/rosie/RosieApiTest.java
- Separated the start/end edit offset validation for addition/the rest of the edit types because the end offset is not relevant when inserting text.
- Added unit and integration tests to cover the new cases.
- Updated a few existing cases to match the new validation logic.
> Ignore end offset incorrectness during validating addition fix edit.

- src/main/java/io/codiga/plugins/jetbrains/graphql/CodigaApiImpl.java
- src/main/java/io/codiga/plugins/jetbrains/graphql/Constants.java
- src/main/java/io/codiga/plugins/jetbrains/rosie/RosieApiImpl.java
- src/main/java/io/codiga/plugins/jetbrains/utils/UserAgentUtils.java
**Problem**
The user-agent of the GraphQL API client is `okhttp`, which is taken from the internal HTTP client from the GraphQL library. We want to make sure we use the `User-Agent` that is used for Rosie.
**Solution**
1. Introduce a class to get the user-agent
2. Use the user-agent and apply it to the graphql client and rosie client altogether.
> fix: user-agent for GraphQL API

- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotator.java
- src/main/java/io/codiga/plugins/jetbrains/starter/RosieRulesCacheUpdateHandler.java
- src/test/java/io/codiga/plugins/jetbrains/starter/RosieRulesCacheUpdateHandlerTest.java
- Updated the range containment check logic in `RosieAnnotator` so that the end offset is inclusive.
- This prevented showing annotations that ended at the document end.
- Updated the default config file modification stamp value in `RosieRulesCacheUpdateHandler`.
- This prevented parsing the Codiga config file when a project was opened without a config file, and the file was created later e.g. via the default rulesets notification.
> Annotation and rulesets bug fixes

- src/main/java/io/codiga/plugins/jetbrains/actions/ActionUtils.java
- src/main/java/io/codiga/plugins/jetbrains/annotators/AnnotationFixOpenBrowser.java
- src/main/java/io/codiga/plugins/jetbrains/annotators/DisableRosieAnalysisFix.java
- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotationFix.java
- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotationIntentionBase.java
- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotator.java
- src/test/java/io/codiga/plugins/jetbrains/rosie/RosieApiTest.java
- Fixed an exception during `TextRange` creation in `RosieAnnotator` when an annotation's start offset is greater than its offset.
- Excluded imaginary editors from the Rosie quick fixes. This is to fix Rollbar item 46.
- Fixed #203
> Various bugfixes

- src/main/java/io/codiga/plugins/jetbrains/annotators/DisableRosieAnalysisFix.java
- src/main/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotator.java
- src/test/java/io/codiga/plugins/jetbrains/annotators/DisableRosieAnalysisFixTest.java
- src/test/java/io/codiga/plugins/jetbrains/annotators/RosieAnnotatorTest.java
- Refactored the `DisableRosieAnalysisFix` to have more control over the formatting.
- E.g. when analysis is performed in a file type that is not supported by the currently used IDE, the indentation could have been off using the previous solution.
- Moved the integration tests to the dedicated `DisableRosieAnalysisFixTest`.
> Refactor the Rosie disable comment fix

- src/main/java/io/codiga/plugins/jetbrains/graphql/LanguageUtils.java
- src/main/java/io/codiga/plugins/jetbrains/rosie/CodigaRulesetConfigs.java
- src/main/java/io/codiga/plugins/jetbrains/starter/RosieStartupActivity.java
- Added default JavaScript ruleset suggestion for JS and TS files.
- Moved some of the logic from `RosieStartupActivity` to `CodigaRulesetConfigs`.
- Updated the logic to show the suggestion as follows
- if Python SDK is configured, show the notification,
- if Python SDK is not configured, but at least one file with one of py, js, jsx, ts or tsx extension is present in the project, then show the notification, and `codiga.yml` is created with a content according to the found file extension.
> Add default ruleset suggestions for JavaScript and TypeScript files.

- src/main/java/io/codiga/plugins/jetbrains/cache/ShortcutCache.java
- Added null check in `ShortcutCache#garbageCollect()` method.
- Related to Rollbar item 49.
> Add null check to shortcut cache garbage collection

- build.gradle.kts
- Added `jackson-databind` and `jackson-dataformat-yaml` dependencies.
- Before, the plugin relied on the `YAMLFactory` and related classes to come from/via the intellij-platform.
- Related to Rollbar item 50.
> Add Jackson dependencies

- src/main/java/io/codiga/plugins/jetbrains/starter/AppStarter.java
- Added a null check, and displaying an error balloon when the user invokes the Snippets or Shortcuts action from the Codiga Coding Assistant notification, and there is no editor open.
- The balloon is displayed for better user experience, so that users know why there is nothing happening in that case.
- This is for Rollbar item 53.
> Add null check and error balloon for Codiga Assistant notification
